package com.craftassignment.urlshortener.model;

import javax.persistence.*;
import java.time.LocalDateTime;
import java.util.Objects;

@Entity(name = "url")
@Table(name = "url")
public class UrlEntity {

    private Long id;

    @Column(name = "original_url")
    private String originalUrl;

    @Column(name = "short_url")
    private String shortUrl;

    @Column(name = "expiry_period")
    private LocalDateTime expiryPeriod;

    public UrlEntity() {
    }

    public UrlEntity(Long id, String fullUrl, String shortUrl, LocalDateTime expiryPeriod) {
        this.id = id;
        this.originalUrl = fullUrl;
        this.shortUrl = shortUrl;
        this.expiryPeriod = expiryPeriod;
    }
    public UrlEntity(String fullUrl) {
        this.originalUrl = fullUrl;
    }

    public UrlEntity(String fullUrl, String shortUrl, LocalDateTime expiryPeriod) {
        this.originalUrl = fullUrl;
        this.shortUrl = shortUrl;
        if(Objects.isNull(expiryPeriod)) this.expiryPeriod = getExpiryPeriod();
        else this.expiryPeriod = expiryPeriod;
    }

    /**
     * @return Autogenerated Id for the url record in the database
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOriginalUrl() {
        return originalUrl;
    }

    public void setOriginalUrl(String originalUrl) {
        this.originalUrl = originalUrl;
    }

    public String getShortUrl() {
        return shortUrl;
    }

    public void setShortUrl(String shortUrl) {
        this.shortUrl = shortUrl;
    }

    @Override
    public String toString() {
        return "Url{" +
                "id=" + id +
                ", fullUrl='" + originalUrl + '\'' +
                ", shortUrl='" + shortUrl + '\'' +
                '}';
    }
    public LocalDateTime getExpiryPeriod() {
        return LocalDateTime.now().plusYears(1);
    }
    public void setExpiryPeriod(LocalDateTime expiryPeriod) {
        if(Objects.isNull(expiryPeriod)) this.expiryPeriod = getExpiryPeriod();
        else this.expiryPeriod = expiryPeriod;

    }

}